---
  - name: Checkout Repo
    tags: update-git
    become: false
    git:
      repo: "{{ item[1].repo }}"
      dest: "/home/{{ item[0] }}{{ item[1].dest }}"
      version: "main"
      key_file: "/home/{{ item[0] }}/.ssh/github"
      ssh_opts: "-o ForwardAgent=yes -o StrictHostKeyChecking=yes"
    with_nested:
      - "{{ users }}"
      - "{{ github }}"
