---
- name: Check for Cert File
  stat:
    path: "/etc/nginx/acme/rosetta.systems/{{ item }}"
  loop:
    - "cert.pem"
    - "key.pem"
    - "fullchain.pem"
  register: certs

- name: Warn Missing Certs
  debug:
    msg: "WARNING: '{{ item.file }}' WAS NOT FOUND, NGINX MAY NOT RELOAD!"
  ignore_errors: yes
  when: not item.exists
  failed_when: not item.exists
  loop: 
  - { exists: "{{ certs.results[0].stat.exists }}", file: "{{ certs.results[0].item }}" }
  - { exists: "{{ certs.results[1].stat.exists }}", file: "{{ certs.results[1].item }}" }
  - { exists: "{{ certs.results[2].stat.exists }}", file: "{{ certs.results[2].item }}" }


- name: Certs Exist
  set_fact:
    certs_exist: "{{ certs.results | map(attribute='stat.exists') is all }}"

- name: Validate Config
  command: >-
    nginx -t
  register: config
  changed_when: false

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: certs_exist and not config.failed | bool
