---
  - name: Create Root Directories
    tags: nginx
    file:
      state: directory
      setype: httpd_sys_content_t
      owner: root
      group: nginx
      mode: 02750
      path: /var/www/html

  - name: Create index.html
    tags: nginx
    copy:
      src: index.html
      dest: /var/www/html

  - name: Setup nginx.conf
    tags: nginx
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: "{{ nginx_conf }}", dest: /etc/nginx/nginx.conf }
      - { src: selinux/nginx.pp, dest: /etc/nginx/nginx.pp}
    notify: Restart Nginx
              
  - name: Start Nginx
    tags: nginx
    service:
      name: nginx
      enabled: true
      state: started  

  - name: Check for Custom Sepolicy
    tags: nginx
    shell:
      cmd: "semodule -l | grep nginx"
    register: custom
    ignore_errors: true
    changed_when: false

  - name: Create Custom Selinux Policy
    tags: nginx
    shell:
      cmd: "semodule -i /etc/nginx/nginx.pp"
    when: custom.rc == 1
