---
  - name: Start Firewalld
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Services
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop: "{{ fwd_services }}"
    notify: Reload Firewalld

  - name: Ports
    firewalld:
      port: "{{ item }}" 
      state: enabled
      permanent: true
      immediate: true
    loop: "{{ fwd_ports }}"
    notify: Reload Firewalld  
