---
- hosts: hybrid

  pre_tasks:

    - name: Update Repository Index
      dnf:
        update_cache: true
        update_only: true

- import_playbook: common.yml
  vars: 
    CURRENT_HOSTS: hybrid

- hosts: hybrid
  roles:
    - git
    - ansible
    - deploy
    - webhooks
