---
- hosts: rosetta

  pre_tasks:

    - name: Update Repository Index
      dnf:
        update_cache: true
        update_only: true

- import_playbook: common.yml
  vars: 
    CURRENT_HOSTS: rosetta

- hosts: rosetta
  roles:
    - git
    - ansible

- hosts: rosetta:&rosetta.systems
  roles:
    - acme.sh

- hosts: rosetta
  roles:
    - deploy
    - rosetta-server
