---
- hosts: workstation

  pre_tasks:

    - name: Update Repository Index
      dnf:
        update_cache: true
        update_only: true

- import_playbook: common.yml
  vars: 
    CURRENT_HOSTS: workstation

- hosts: workstation
  roles:
    # TODO: switched git/ansible, ensure still works
    - git
    - ansible
    - deploy
    - webhooks
